//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Forum_Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forum_Questions()
        {
            this.Forum_Answers = new HashSet<Forum_Answers>();
        }
    
        public int QId { get; set; }
        [Required(ErrorMessage = "*Required!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "*Required!")]
        public string Description { get; set; }
        public Nullable<int> FK_UserId { get; set; }
        public System.DateTime PostDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forum_Answers> Forum_Answers { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
